wcdb/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$',  'views.home'),
    url(r'^about/$', 'views.about'),
    url(r'^', include('wcdb.crises.urls')),

    #Heroku setting to serve static files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),   

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

wcdb/crises/models.py
from django.db import models

class Crises(models.Model):
	name = models.CharField(max_length=100)
	kind = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name

class People(models.Model):
	name = models.CharField(max_length=100)
	kind = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name	

class Organizations(models.Model):
	name = models.CharField(max_length=100)
	kind = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name	

class CrisesMaps(models.Model):
	maps = models.URLField(max_length=500)
	crisis = models.ForeignKey(Crises)

class CrisesImages(models.Model):
	image = models.URLField(max_length=500)
	crisis = models.ForeignKey(Crises)

class CrisesVideos(models.Model):
	video = models.URLField(max_length=500)
	crisis = models.ForeignKey(Crises)

class CrisesTwitter(models.Model):
	twitter = models.URLField(max_length=500)
	widget_id = models.CharField(max_length=20)
	crisis = models.ForeignKey(Crises)

class CrisesHelp(models.Model):
	help = models.CharField(max_length=500)
	crisis = models.ForeignKey(Crises)

class CrisesResourses(models.Model):
	resourses = models.CharField(max_length=500)	
	crisis = models.ForeignKey(Crises)

class CrisesLinks(models.Model):
	external_links = models.URLField(max_length=500)
	crisis = models.ForeignKey(Crises)

class CrisesCitations(models.Model):
	citations = models.URLField(max_length=500)
	crisis = models.ForeignKey(Crises)	

class CrisesData(models.Model):
	crisis = models.OneToOneField(Crises, primary_key=True)
	description = models.CharField(max_length=2000)
	location = models.CharField(max_length=500)		
	start_date = models.DateField()
	end_date = models.DateField()
	human_impact = models.CharField(max_length=500)
	economic_impact = models.CharField(max_length=500)

	people = models.ManyToManyField(People)
	orgs = models.ManyToManyField(Organizations)

	def __unicode__(self):
		return self.crisis.name

class PeopleMaps(models.Model):
	maps = models.URLField(max_length=500)
	people = models.ForeignKey(People)

class PeopleImages(models.Model):
	image = models.URLField(max_length=500)
	people = models.ForeignKey(People)
	
class PeopleVideos(models.Model):
	video = models.URLField(max_length=500)
	people = models.ForeignKey(People)

class PeopleTwitter(models.Model):
	twitter = models.URLField(max_length=500)
	widget_id = models.CharField(max_length=20)
	people = models.ForeignKey(People)

class PeopleLinks(models.Model):
	external_links = models.URLField(max_length=500)
	people = models.ForeignKey(People)

class PeopleCitations(models.Model):
	citations = models.URLField(max_length=500)
	people = models.ForeignKey(People)	

class PeopleData(models.Model):
	person = models.OneToOneField(People, primary_key=True)
	description = models.CharField(max_length=2000)
	dob = models.DateField()
	location = models.CharField(max_length=500)		

	crises = models.ManyToManyField(Crises)
	orgs = models.ManyToManyField(Organizations)

	def __unicode__(self):
		return self.person.name

class ContactInfo(models.Model):
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=200)
	email = models.EmailField(max_length=50)
	phone = models.CharField(max_length=50)

class OrgMaps(models.Model):
	maps = models.URLField(max_length=500)
	org = models.ForeignKey(Organizations)

class OrgImages(models.Model):
	image = models.URLField(max_length=500)
	org = models.ForeignKey(Organizations)

class OrgVideos(models.Model):
	video = models.URLField(max_length=500)
	org = models.ForeignKey(Organizations)

class OrgTwitter(models.Model):
	twitter = models.URLField(max_length=500)
	widget_id = models.CharField(max_length=20)
	org = models.ForeignKey(Organizations)

class OrgLinks(models.Model):
	external_links = models.URLField(max_length=500)
	org = models.ForeignKey(Organizations)

class OrgCitations(models.Model):
	citations = models.URLField(max_length=500)
	org = models.ForeignKey(Organizations)	

class OrganizationsData(models.Model):
	org = models.OneToOneField(Organizations, primary_key=True)
	date_established = models.DateField()
	description = models.CharField(max_length=2000)
	location = models.CharField(max_length=500)	

	contact_info = models.OneToOneField(ContactInfo)
	crises = models.ManyToManyField(Crises)
	people = models.ManyToManyField(People)

	def __unicode__(self):
		return self.org.name

wcdb/templates/about.html
{% extends "base.html" %}

{% block title %}World Crisies Database | About{% endblock %}

{% block about %}
<center><h1>About The TCP Connections</h1></center>
<br><br>
<div class = "col-md-12">
	<a href = "https://github.com/alek0313"><h2>Anwar (Alek) Merani</h2></a>
	<p>is a fifth year senior graduating with a B.S. in Computer Science. He enjoys music shows and food trucks around Austin when he's not slaving away in the computer lab.</p>
</div><br>
<div class = "col-md-12">
	<a href = "https://github.com/tangurano"><h2>Charles Tang</h2></a>
	<p>is an junior computer science student at the University of Texas at Austin. His last name means "soup" in Chinese.</p>
</div><br>
<div class = "col-md-12">
	<a href = "https://github.com/maxxb"><h2>Maxx Boehme</h2></a>
	<p>is an undergraduate computer science student on his fourth year at the University of Texas at Austin. He is planning on having a future career in computer security but enjoys making games in his free time.</p>
</div><br>
<div class = "col-md-12">
	<a href = "https://github.com/pglass"><h2>Paul Glass</h2></a>
	<p>has an aversion to writing about himself.</p>
</div><br>
<div class = "col-md-12">
	<a href = "http://scott-enriquez.net"><h2>Scottie Enriquez</h2></a>
	<p>is a graduating senior double-majoring in computer science and Asian studies. As of January 2014, he's moved to Anchorage, Alaska. He may or may not have frozen to death.</p>
</div>
<br>
{% endblock %}

wcdb/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel = "stylesheet" type = "text/css" href = "http://fonts.googleapis.com/css?family=Open+Sans:300,400,700,400italic">
    <link rel = "stylesheet" type = "text/css" href = "/static/css/bootstrap.css">
    <link rel = "stylesheet" type = "text/css" href = "/static/css/wcdb-style.css">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  </head>
  <body>
    <!-- Body container -->
    <div class = "container">
      <!-- Top-level menu -->
      <nav class = "navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class = "container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">WCDB</a>
              </div>
              <div class="collapse navbar-collapse navbar-1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href = "/crises/">Crises</a></li>
                    <li><a href = "/organizations/">Organizations</a></li>
                    <li><a href = "/people/">People</a></li>
                    <li><a href = "/wordcloud/">Word Clouds</a></li>
                    <li><a href = "/sqlqueries/">Queries</a></li>
                    <li><a href = "/tests/">Tests</a></li>
                    <li><a href = "/about/">About Us</a></li>
                  </ul>

                    <form class="col-xs-6 col-md-2 navbar-search pull-left" role="search" action="/search" method="get" style="padding: 10px">
                      <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search" name="query">
                        <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                      </div>
                    </form>
                </ul>
              </div>
            </div>
      </nav>

        {% block home-desc %}
        {% endblock %}

        {% block home-carousel %}
        {% endblock %}

        {% block links %} 
        {% endblock %}

        {% block about %}
        {% endblock %}

        {% block crisis %}  
        {% endblock %}

        {% block wordcloud %}  
        {% endblock %}

        {% block sqlquery %}
        {% endblock %}

        {% block test_results %}
        {% endblock %}

        {% block results %}  
        {% endblock %}

    </div><!-- /.container --> 

    <div id="footer">
      <div class="container">
        <center>
        {% block copyright %}  
        {% endblock %} 
      </center>
      </div>
    </div>  
      <script src="https://code.jquery.com/jquery.js"></script>
      <script src="/static/js/bootstrap.js"></script>
  </body>
</html>

wcdb/templates/crises_index.html
{% extends "base.html" %}

{% block title %}World Crisies Database | {{crisis_data.crisis.name}}{% endblock %}

{% block crisis %}  
<center><h1>{{crisis_data.crisis.name}}</h1></center>
<br>
<div class="panel-group" id="accordion" style="height: 348px;">
	<div class="panel panel-default">
		<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          	Overview
        	</a>
      		</h1>
    	</div>
    	<div id="collapseOne" class="panel-collapse collapse in">
      		<div class="panel-body">
        		<p>{{crisis_data.description}}</p>
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
   		<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          		Additional Information
        	</a>
      		</h1>
    	</div>
    	<div id="collapseTwo" class="panel-collapse collapse">
      		<div class="panel-body">
	        	<ul>
					<li><b>Type</b>: {{crisis_data.crisis.kind}}</li>
					<li><b>Time Frame</b>: {{crisis_data.start_date}} to {{crisis_data.end_date}}</li>
					<li><b>Location</b>: {{crisis_data.location}}</li>
					<li><b>Human Impact</b>: {{crisis_data.human_impact}}</li>
					<li><b>Economic Impact</b>: {{crisis_data.economic_impact}}</li>
					<li><b>Ways to help</b>: 
						{% for x in crisis_data.crisis.criseshelp_set.all %}
							<p>{{x.help}}</p>
						{% endfor %}
					</li>
					<li><b>Resources Needed</b>:
						{% for x in crisis_data.crisis.crisesresourses_set.all %}
							<p>{{x.resourses}}</p>
						{% endfor %}
					</li>
					<li><b>External Links</b>: 
						{% for x in crisis_data.crisis.criseslinks_set.all %}
							<a href="{{x.external_links}}">{{x.external_links}}</a><br>
						{% endfor %}
					</li>
					<li><b>Citations</b>: 
						{% for x in crisis_data.crisis.crisescitations_set.all %}
							<a href="{{x.citations}}">{{x.citations}}</a><br>
						{% endfor %}
					</li>
					<li><b>Related people</b>:
						{% for p in crisis_data.people.all %}
							<a href="../../people/{{ p.id }}"><p>{{p.name}}</p></a>
						{% endfor %}	
					</li>
					<li><b>Related organizations</b>:
						{% for o in crisis_data.orgs.all %}
							<a href="../../organizations/{{ o.id }}"><p>{{o.name}}</p></a>
						{% endfor %}	
					</li>
				</ul>
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          		Images
        	</a>
      		</h1>
    	</div>
    	<div id="collapseThree" class="panel-collapse collapse">
      		<div class="panel-body">
      			<br>
        		{% for x in crisis_data.crisis.crisesimages_set.all %}
					<center><a><img src = "{{x.image}}"></a></center><br>
				{% endfor %}
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          		Videos
        	</a>
      		</h1>
    	</div>
    	<div id="collapseFour" class="panel-collapse collapse">
      		<div class="panel-body">
      			<br>
      			{% for x in crisis_data.crisis.crisesvideos_set.all %}
					<center><iframe width="420" height="315" src="{{x.video}}" frameborder="0" allowfullscreen></iframe></center><br>
				{% endfor %}
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
	      	<h1 class="panel-title">
	        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
	        Maps
	        </a>
	      	</h1>
    	</div>
    	<div id="collapseFive" class="panel-collapse collapse">
      		<div class="panel-body">
      			<br>
      			{% for x in crisis_data.crisis.crisesmaps_set.all %}
					<center><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="{{x.maps}}"></iframe></center><br>
				{% endfor %}
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          	Public Opinion
        	</a>
      		</h1>
    	</div>
    	<div id="collapseSix" class="panel-collapse collapse">
    		<br>
    		{% for x in crisis_data.crisis.crisestwitter_set.all %}
				<center><a class="twitter-timeline"  href="{{x.twitter}}"  data-widget-id="{{x.widget_id}}"></a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><center><br>
			{% endfor %}
    	</div>
  	</div>
</div>

{% endblock %}

wcdb/templates/home.html
{% extends "base.html" %}

{% block home-desc %}
        <center><h1>{% block title %}World Crises Database{% endblock %}</h1></center>
        <br>
        <p1>With the explosion of advanced mobile technologies and social media, news and global awareness are now more prolific than ever before. In the digital age, people want news as quickly as it takes to load a page. The World Crisis Database was created with this notion in mind. Powered by the latest tools and frameworks, The TCP Connections strive to bring awareness about crises and issues worldwide in a clean, organized, and readable format.</p1>
        <br><br><br>
{% endblock %}


{% block home-carousel %}
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="item homeCarousel active">
              <img src="http://assets.natgeotv.com/Photos/40/100832.jpg">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Crises</h1>
                  <p>At any given time there are thousands of crises occuring throughout the world.</p>
                  <p><a class="btn btn-lg btn-primary" href="crises/" role="button">Stay informed</a></p>
                </div>
              </div>
            </div>
            <div class="item homeCarousel">
              <img src="http://i.huffpost.com/gen/1160224/thumbs/o-UNITED-NATIONS-facebook.jpg">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Organizations</h1>
                  <p>Groups both combat and cause the crises of the world.</p>
                  <p><a class="btn btn-lg btn-primary" href="organizations/" role="button">Stay informed</a></p>
                </div>
              </div>
            </div>
            <div class="item homeCarousel">
              <img src="http://rack.1.mshcdn.com/media/ZgkyMDEyLzEyLzA0LzdlL2Nyb3dkc291cmNlLmJRay5qcGcKcAl0aHVtYgkxMjAweDYyNyMKZQlqcGc/d0ed0e96/d8e/crowdsourced-philanthropy-is-it-worth-the-risk--9a6b5d8a3e.jpg">
              <div class="container">
                <div class="carousel-caption">
                  <h1>People</h1>
                  <p>These are the public figures directly involved with world crises.</p>
                  <p><a class="btn btn-lg btn-primary" href="people/" role="button">Stay informed</a></p>
                </div>
              </div>
            </div>
          </div>
          <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div><!-- /.carousel -->
{% endblock %}

wcdb/templates/org_index.html
{% extends "base.html" %}

{% block title %}World Crisies Database | {{org_data.org.name}}{% endblock %}

{% block crisis %}  
<center><h1>{{org_data.org.name}}</h1></center>
<br>
<div class="panel-group" id="accordion" style="height: 348px;">
	<div class="panel panel-default">
		<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          	Overview
        	</a>
      		</h1>
    	</div>
    	<div id="collapseOne" class="panel-collapse collapse in">
      		<div class="panel-body">
        		<p>{{org_data.description}}</p>
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
   		<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          		Additional Information
        	</a>
      		</h1>
    	</div>
    	<div id="collapseTwo" class="panel-collapse collapse">
      		<div class="panel-body">
	        	<ul>
					<li><b>Type</b>: {{org_data.org.kind}}</li>
					<li><b>Date Established</b>: {{org_data.date_established}}</li>
					<li><b>Location</b>: {{org_data.location}}</li>
					<li><b>Name</b>: {{org_data.contact_info.name}}</li>
          <li><b>Address</b>: {{org_data.contact_info.address}}</li>
          <li><b>Email</b>: {{org_data.contact_info.email}}</li>
          <li><b>Phone</b>: {{org_data.contact_info.phone}}</li>
					<li><b>External Links</b>: 
						{% for x in org_data.org.orglinks_set.all %}
							<a href="{{x.external_links}}">{{x.external_links}}</a><br>
						{% endfor %}
					</li>
					<li><b>Citations</b>: 
						{% for x in org_data.org.orgcitations_set.all %}
							<a href="{{x.citations}}">{{x.citations}}</a><br>
						{% endfor %}
					</li>
					<li><b>Related people</b>:
						{% for p in org_data.people.all %}
							<a href="../../people/{{ p.id }}"><p>{{p.name}}</p></a>
						{% endfor %}	
					</li>
					<li><b>Related crises</b>:
						{% for o in org_data.crises.all %}
							<a href="../../crises/{{ o.id }}"><p>{{o.name}}</p></a>
						{% endfor %}	
					</li>
				</ul>
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          		Images
        	</a>
      		</h1>
    	</div>
    	<div id="collapseThree" class="panel-collapse collapse">
      		<div class="panel-body">
      			<br>
        		{% for x in org_data.org.orgimages_set.all %}
					<center><a><img src = "{{x.image}}"></a></center><br>
				{% endfor %}
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          		Videos
        	</a>
      		</h1>
    	</div>
    	<div id="collapseFour" class="panel-collapse collapse">
      		<div class="panel-body">
      			<br>
      			{% for x in org_data.org.orgvideos_set.all %}
					<center><iframe width="420" height="315" src="{{x.video}}" frameborder="0" allowfullscreen></iframe></center><br>
				{% endfor %}
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
	      	<h1 class="panel-title">
	        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
	        Maps
	        </a>
	      	</h1>
    	</div>
    	<div id="collapseFive" class="panel-collapse collapse">
      		<div class="panel-body">
      			<br>
      			{% for x in org_data.org.orgmaps_set.all %}
					<center><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="{{x.maps}}"></iframe></center><br>
				{% endfor %}
      		</div>
    	</div>
  	</div>
  	<div class="panel panel-default">
    	<div class="panel-heading">
      		<h1 class="panel-title">
        	<a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          	Public Opinion
        	</a>
      		</h1>
    	</div>
    	<div id="collapseSix" class="panel-collapse collapse">
    		<br>
    		{% for x in org_data.org.orgtwitter_set.all %}
				<center><a class="twitter-timeline"  href="{{x.twitter}}"  data-widget-id="{{x.widget_id}}"></a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><center><br>
			{% endfor %}
    	</div>
  	</div>
</div>

{% endblock %}

wcdb/templates/people_index.html
{% extends "base.html" %}

{% block title %}World Crisies Database | {{people_data.person.name}}{% endblock %}

{% block crisis %}
<center><h1>{{people_data.person.name}}</h1></center>
<br>
<div class="panel-group" id="accordion" style="height: 348px;">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
					Overview
				</a>
			</h1>
		</div>
		<div id="collapseOne" class="panel-collapse collapse in">
			<div class="panel-body">
			<p>{{people_data.description}}</p>
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
					Additional Information
				</a>
			</h1>
		</div>
		<div id="collapseTwo" class="panel-collapse collapse">
			<div class="panel-body">
				<ul>
					<li><b>Date of Birth</b>: {{people_data.dob}}</li>
					<li><b>Location</b>: {{people_data.location}}</li>
					<li><b>Type</b>: {{people_data.person.kind}}</li>
					<li><b>External Links</b>:
					{% for x in people_data.person.peoplelinks_set.all %}
						<a href="{{x.external_links}}">{{x.external_links}}</a><br>
					{% endfor %}
					</li>
					<li><b>Citations</b>:
					{% for x in people_data.person.peoplecitations_set.all %}
						<a href="{{x.citations}}">{{x.citations}}</a><br>
					{% endfor %}
					</li>
					<li><b>Related crises</b>:
					{% for c in people_data.crises.all %}
						<a href="../../crises/{{ c.id }}"><p>{{c.name}}</p></a>
					{% endfor %}
					</li>
					<li><b>Related organizations</b>:
					{% for o in people_data.orgs.all %}
						<a href="../../organizations/{{ o.id }}"><p>{{o.name}}</p></a>
					{% endfor %}
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
					Images
				</a>
			</h1>
		</div>
		<div id="collapseThree" class="panel-collapse collapse">
			<div class="panel-body">
				<br>
			{% for x in people_data.person.peopleimages_set.all %}
				<center><a><img src = "{{x.image}}"></a></center><br>
			{% endfor %}
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h1 class="panel-title">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
				Videos
			</a>
		</h1>
	</div>
	<div id="collapseFour" class="panel-collapse collapse">
		<div class="panel-body">
			<br>
			{% for x in people_data.person.peoplevideos_set.all %}
				<center><iframe width="420" height="315" src="{{x.video}}" frameborder="0" allowfullscreen></iframe></center><br>
			{% endfor %}
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h1 class="panel-title">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
				Maps
			</a>
		</h1>
	</div>
	<div id="collapseFive" class="panel-collapse collapse">
		<div class="panel-body">
			<br>
			{% for x in people_data.person.peoplemaps_set.all %}
				<center><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="{{x.maps}}"></iframe></center><br>
			{% endfor %}
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h1 class="panel-title">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
				Public Opinion
			</a>
		</h1>
	</div>
	<div id="collapseSix" class="panel-collapse collapse">
		<br>
		{% for x in people_data.person.peopletwitter_set.all %}
			<center><a class="twitter-timeline"  href="{{x.twitter}}"  data-widget-id="{{x.widget_id}}"></a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><center><br>
		{% endfor %}
	</div>
</div>
</div>

{% endblock %}